Columns don't provide a WYSIWYG experience in edit mode #208
xwikisas/xwiki-pro-macros pull request #233
Opened 2024-03-28 14:13 UTC by Farcasut

I've modified the structure of the cke wrappers using CSS and JavaScript to make the page look as expected. To be more precise, I've made the main wrapper a flex container to display each column on the same line and moved the width from the original element to its wrapper to keep the ratio used in the view mode.

2024-03-28 14:15 UTC, Farcasut commented
![image](https://github.com/xwikisas/xwiki-pro-macros/assets/92780090/08c8f8b7-ec44-4cd3-9fa4-eeb29c90e93c)

2024-03-29 08:54 UTC, trrenty requested changes
Some changes needed

2024-03-29 08:54 UTC, trrenty commented on xwiki-pro-macros-ui/src/main/resources/Confluence/Macros/Section.xml
> +.macro-section {
Duplicate code

2024-03-29 08:54 UTC, trrenty commented on xwiki-pro-macros-ui/src/main/resources/Confluence/Macros/Section.xml
> +      <code>require(['jquery'], ($) =&gt; {
you should also require this jsx code in the section macro code

2024-03-29 08:54 UTC, trrenty commented on xwiki-pro-macros-ui/src/main/resources/Confluence/Macros/Section.xml
> +      <use/>
onDemand. Im not sure whats the default, but it doesnt hurt to have it specified.

2024-03-29 09:22 UTC, trrenty approved these changes

2024-04-02 08:47 UTC, merged

2024-04-02 09:22 UTC, mflorea commented on xwiki-pro-macros-ui/src/main/resources/Confluence/Macros/Column.xml
> +  (% class="macro-column" data-width="$xcontext.macro.params.width" $style %)(((
Missing escaping. 3 lines above too.